// Copies the game's web build into public/ (served as static assets) and records its build id.
//
//   node scripts/sync-build.mjs [path/to/build-web]     (default: ../build-web)
//
// Only the files players need are copied; the ROM is never part of the build.
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const buildDir = resolve(process.argv[2] || join(root, '..', 'build-web'));
const publicDir = join(root, 'public');

const FILES = ['index.html', 'pd-web.js', 'pd-host.js', 'nethost.js', 'net-client.js', 'manifest.webmanifest', 'sw.js',
  'icons', 'pd.js', 'pd.wasm', 'pd.snap.json'];

for (const f of FILES) {
  if (!existsSync(join(buildDir, f))) {
    console.error(`missing ${join(buildDir, f)}: build the game first (web/build.sh)`);
    process.exit(1);
  }
}

rmSync(publicDir, { recursive: true, force: true });
mkdirSync(publicDir, { recursive: true });
for (const f of FILES) {
  cpSync(join(buildDir, f), join(publicDir, f), { recursive: true });
}

// versioned script URLs, as web/server.js serves them: a cached old script must never run
// against a newer game
const indexPath = join(publicDir, 'index.html');
writeFileSync(indexPath, readFileSync(indexPath, 'utf8').replace(/<script src="([^"?:]+\.js)"><\/script>/g, (tag, src) => {
  const hash = createHash('sha1').update(readFileSync(join(publicDir, src))).digest('hex').slice(0, 10);
  return `<script src="${src}?v=${hash}"></script>`;
}));

// the same headers web/server.js sends
writeFileSync(join(publicDir, '_headers'), `/*
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp
  Cross-Origin-Resource-Policy: same-origin
  X-Content-Type-Options: nosniff
  Cache-Control: no-cache

/manifest.webmanifest
  Content-Type: application/manifest+json; charset=utf-8
`);

// clients and the lobby must run the same pd.wasm (snapshots only work between identical builds)
const buildId = createHash('sha1').update(readFileSync(join(buildDir, 'pd.wasm'))).digest('hex').slice(0, 12);
writeFileSync(join(root, 'src', 'build-info.js'),
  `// generated by scripts/sync-build.mjs\nexport const BUILD_ID = ${JSON.stringify(buildId)};\n`);

console.log(`public/ updated from ${buildDir}, build ${buildId}`);
